base/urls.py
from django.urls import path
from .views import index 


app_name="base"
urlpatterns = [
    path('', index,name="index"),
]

cantine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("base.urls")),
    path('menu/',include("menu.urls")),
    path('plat/',include("plat.urls")),
]

menu/urls.py
from django.urls import path
from .views import index,add, update, delete 




app_name="menu"
urlpatterns = [
    path('', index,name="index"),
    path('add',add,name="add"),
    path('update/<int:id>',update,name="update-menu"),
    path('delete/<int:id>',delete,name="delete-menu"),
]

plat/urls.py
from django.urls import path
from .views import index,add, update, delete 




app_name="plat"
urlpatterns = [
    path('', index,name="index"),
    path('add',add,name="add"),
    path('update/<int:id>',update,name="update-plat"),
    path('delete/<int:id>',delete,name="delete-plat"),
]

menu/models/menu_model.py
from django.db import models
from base.models.helpers.date_time_model import DateTimeModel

# Create your models here.

class MenuModel(DateTimeModel):
    plat = models.OneToOneField('plat.PlatModel', on_delete=models.CASCADE)
    creation_date = models.DateTimeField()

    class Meta:
        verbose_name = "Menu"
        verbose_name_plural = "Menus"

    def __str__(self):
        return f"{self.plat},{self.created_at}"

plat/models/plat_model.py
from django.db import models
from base.models.helpers.named_date_time_model import NamedDateTimeModel

# Create your models here.

class PlatModel(NamedDateTimeModel):

    summary = models.CharField(max_length=20)
    
    class Meta:
        verbose_name = "Plat"
        verbose_name_plural = "Plats"

    def __str__(self):
        return f"{self.name}"

menu/forms/menu_form.py
from django import forms
from menu.models.menu_model import MenuModel


class MenuForm(forms.ModelForm):
    class Meta:
        model = MenuModel
        fields = ['plat', 'creation_date',]
        widgets = {
            'creation_date': forms.DateInput(attrs={'type':'date'}),
        }

plat/forms/plat_form.py
from django import forms
from plat.models.plat_model import PlatModel


class PlatForm(forms.ModelForm):
    class Meta:
        model = PlatModel
        fields = ['name', 'summary',]
        

base/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, "base.html")

menu/views.py
from django.shortcuts import render, redirect
from menu.forms.menu_form import MenuForm
from menu.models.menu_model import MenuModel


def index(request):
    rech_menu = request.GET.get('rech')
    if rech_menu:
        menus = MenuModel.objects.filter(plat__icontains=rech_menu)
        context= { 'menus': menus,
                  'rech_menu': rech_menu
                  }
    else:
        menus = MenuModel.objects.all()
        menu_count = MenuModel.objects.count()
        context = {
            'menus':menus,
            'menu_count': menu_count
        }
    return render(request, "menu/index.html", context)


def add(request):
    context={"title":"Ajouter un menu"}

    if request.method == "POST":
        print(request.POST)
        form =MenuForm(request.POST)
        context["form"] = form
        if form.is_valid():
            print("form is valid")
            print(form.cleaned_data)
            form.save()
            return redirect('menu:index')
        else:
            return render(request,"menu/add.html")

    
    form = MenuForm()
    context["form"] = form

    return render(request,"menu/add.html",context)


def update(request, id ):
    menu = MenuModel.objects.get(id=id)

    context = {"title":"Modifier un menu"}


    if request.method == "POST":
        form = MenuForm(request.POST, instance=menu)
        if form.is_valid():
            form.save()
            return redirect('menu:index')
        
    form = MenuForm(instance = menu)

    context["form"] = form

    return render(request,"menu/add.html",context)

def delete(request ,id):
    student = MenuModel.objects.get(id = id)
    student.delete()
    return redirect('menu:index')

plat/views.py
from django.shortcuts import render, redirect
from plat.forms.plat_form import PlatForm
from plat.models.plat_model import PlatModel


def index(request):
    rech_plat = request.GET.get('rech')
    if rech_plat:
        plats = PlatModel.objects.filter(name__icontains=rech_plat)
        context= { 'plats': plats,
                  'rech_user': rech_plat
                  }
    else:
        plats = PlatModel.objects.all()
        plat_count = PlatModel.objects.count()
        context = {
            'plats':plats,
            'plat_count': plat_count
        }
    return render(request, "plat/index.html", context)


def add(request):
    context={"title":"Ajouter un plat"}

    if request.method == "POST":
        print(request.POST)
        form =PlatForm(request.POST)
        context["form"] = form
        if form.is_valid():
            print("form is valid")
            print(form.cleaned_data)
            form.save()
            return redirect('plat:index')
        else:
            return render(request,"plat/add.html")

    # context={'elev_form':elev_form}
    form = PlatForm()
    context["form"] = form

    return render(request,"plat/add.html",context)


def update(request, id ):
    plat = PlatModel.objects.get(id=id)

    context = {"title":"Modifier un plat"}


    if request.method == "POST":
        form = PlatForm(request.POST, instance=plat)
        if form.is_valid():
            form.save()
            return redirect('plat:index')
        
    form = PlatForm(instance = plat)

    context["form"] = form

    return render(request,"plat/add.html",context)

def delete(request ,id):
    student = PlatModel.objects.get(id = id)
    student.delete()
    return redirect('plat:index')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

{% block head %}
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="apple-touch-icon" sizes="76x76" href="">
<link rel="icon" type="image/png" href="">

<title>
    Ma cantine scolaire
</title>


<!--     Fonts and icons     -->
<link rel="stylesheet" type="text/css"
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700"/>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />


<!-- Nucleo Icons -->
<link href=" {% static 'css/nucleo-icons.css' %}" rel="stylesheet"/>
<link href=" {% static 'css/nucleo-svg.css' %}" rel="stylesheet"/>

<!-- Font Awesome Icons -->
<script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>

<!-- Material Icons -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">

<!-- CSS Files -->


<link id="pagestyle" href=" {% static 'css/material-dashboard.css' %}" rel="stylesheet"/>


<!-- Nepcha Analytics (nepcha.com) -->
<!-- Nepcha is a easy-to-use web analytics. No cookies and fully compliant with GDPR, CCPA and PECR. -->
<script defer data-site="YOUR_DOMAIN_HERE" src="https://api.nepcha.com/js/nepcha-analytics.js"></script>


</head>

{% endblock head %}

<body class="g-sidenav-show  bg-gray-100">


<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark"
       id="sidenav-main">

    <div class="sidenav-header">
        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
           aria-hidden="true" id="iconSidenav"></i>
        <a class="navbar-brand m-0" href="{% url 'base:index' %}"
           target="_blank">
            <img src="./assets/img/logo-ct.png" class="navbar-brand-img h-100" alt="main_logo">
            <span class="ms-1 font-weight-bold text-white">Ma cantine</span>
        </a>
    </div>


    <hr class="horizontal light mt-0 mb-2">

    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
        <ul class="navbar-nav">


            <li class="nav-item">
                <a class="nav-link text-white " href="{% url 'menu:index' %}">

                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <span class="material-symbols-outlined">menu_book</span>
                    </div>

                    <span class="nav-link-text ms-1">Menus</span>
                </a>
            </li>


            <li class="nav-item">
                <a class="nav-link text-white " href="{% url 'plat:index' %}">

                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <span class="material-symbols-outlined">local_cafe</span>
                    </div>

                    <span class="nav-link-text ms-1">Plats</span>
                </a>
            </li>

        </ul>
    </div>

</aside>

<main class="main-content border-radius-lg ">
    
    {% block content %}

    {% endblock content %}


    <div class="container-fluid py-4">

        <footer class="footer py-4  ">
            <div class="container-fluid">
                <div class="row align-items-center justify-content-lg-between">
                    <div class="col-lg-6 mb-lg-0 mb-4">
                        <div class="copyright text-center text-sm text-muted text-lg-start">
                            © <script>
                            document.write(new Date().getFullYear())
                        </script>
                            ADA
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </div>


</main>


<!--   Core JS Files   -->

<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
<script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
</script>

<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>


<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{% static 'js/material-dashboard.min.js' %}"></script>
</body>

</html>

templates/menu/add.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<main class="main-content  mt-0">
    <section>
        <div class="page-header min-vh-100">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12 col-lg-12 col-md-12 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-12">
                        <div class="card card-plain">
                            <div class="card-header">
                                <h4 class="font-weight-bolder">{{title}}</h4>
                            </div>
                            <div class="card-body">
                                <form role="form" method="POST">
                                    {% csrf_token %}
            
                                    {{form}}
                                    <div class="text-center">
                                        <button type="submit"
                                                class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">
                                            Enregistrer
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock content %}

templates/menu/index.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="">
  <link rel="icon" type="image/png" href="../assets/img/favicon.png">
  <title>
    Liste des menus
  </title>
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
  <!-- CSS Files -->
  <link id="pagestyle" href="../assets/css/material-dashboard.css" rel="stylesheet" />
  <!-- Nepcha Analytics (nepcha.com) -->
  <!-- Nepcha is a easy-to-use web analytics. No cookies and fully compliant with GDPR, CCPA and PECR. -->
  <script defer data-site="YOUR_DOMAIN_HERE" src="https://api.nepcha.com/js/nepcha-analytics.js"></script>
</head>

{% endblock head %}

{% block content %}
<main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
      <div class="container-fluid py-1 px-3">


        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          <ul class="navbar-nav  justify-content-start">
            <li class="nav-item d-flex align-items-center">
              <a class="btn btn-outline-warning btn-sm mb-0 me-3" href="{% url 'menu:add' %}">Ajouter un menu</a>
            </li>
          </ul>
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
            <form action="GET">
            <div class="input-group input-group-outline">
              <label class="form-label">Recherche par nom</label>
              <input type="text" id="" name="rech" value="{{rech_menu}}" placeholder="Recherche" class="form-control">
            </div>
          </div>
          <ul class="navbar-nav  justify-content-end">
            <li class="nav-item d-flex align-items-center">
              <button class="btn btn-outline-primary btn-sm mb-0 me-3">Recherche</button>
            </li>
          </ul>
        </form>
        </div>
      </div>
    </nav>
    <!-- End Navbar -->
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-warning shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Liste des menus {{menu_count}}</h6>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Date</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Plat</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2 align-items-center"></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for menu in menus %}
                    <tr>
                      <td>
                        <div class="d-flex px-2 py-1">
                          <div class="d-flex flex-column justify-content-center">
                            <h6 class="mb-0 text-sm">{{menu.creation_date}}</h6>
                          </div>
                        </div>
                      </td>
                      <td>
                        <div class="d-flex px-2 py-1">
                          <div class="d-flex flex-column justify-content-center">
                            <h6 class="mb-0 text-sm">{{menu.plat.name}}</h6>
                          </div>
                        </div>
                      </td>
                      <td class="align-middle text-center text-sm">
                        <a href="{% url 'menu:update-menu' menu.id %}" class="badge badge-sm bg-gradient-success" h>Modifier</a>
                        <a href="{% url 'menu:delete-menu' menu.id %}" class="badge badge-sm bg-gradient-danger">Supprimer</a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
  
{% endblock content %}

templates/plat/add.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<main class="main-content  mt-0">
    <section>
        <div class="page-header min-vh-100">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12 col-lg-12 col-md-12 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-12">
                        <div class="card card-plain">
                            <div class="card-header">
                                <h4 class="font-weight-bolder">{{title}}</h4>
                            </div>
                            <div class="card-body">
                                <form role="form" method="POST">
                                    {% csrf_token %}
            
                                    {{form}}
                                    <div class="text-center">
                                        <button type="submit"
                                                class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">
                                            Enregistrer
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock content %}

templates/plat/index.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
      <div class="container-fluid py-1 px-3">


        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          <ul class="navbar-nav  justify-content-start">
            <li class="nav-item d-flex align-items-center">
              <a class="btn btn-outline-warning btn-sm mb-0 me-3" href="{% url 'plat:add' %}">Ajouter un plat</a>
            </li>
          </ul>
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
            <form method="GET">
            <div class="input-group input-group-outline">
              <label class="form-label">Recherche par nom</label>
              <input type="text" id="" name="rech" value="{{rech_plat}}" placeholder="Recherche" class="form-control">
            </div>
          </div>
          <ul class="navbar-nav  justify-content-end">
            <li class="nav-item d-flex align-items-center">
              <button onclick="" class="btn btn-outline-primary btn-sm mb-0 me-3">Recherche</button>
            </li>
          </ul>
        </form>
        </div>
      </div>
    </nav>
    <!-- End Navbar -->
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-warning shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Liste des plats {{plat_count}}</h6>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Libelle</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2 align-items-center"></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for plat in plats %}
                    <tr>
                      <td>
                        <div class="d-flex px-2 py-1">
                          <div class="d-flex flex-column justify-content-center">
                            <h6 class="mb-0 text-sm">{{plat.name}}</h6>
                          </div>
                        </div>
                      </td>
                      <td class="align-middle text-center text-sm">
                        <a href="{% url 'plat:update-plat' plat.id %}" class="badge badge-sm bg-gradient-success">Modifier</a>
                        <a href="{% url 'plat:delete-plat' plat.id %}" class="badge badge-sm bg-gradient-danger">Supprimer</a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
 
{% endblock content %}